### ISSUE TITLE
Could you update please ? :)

### ISSUE THREAD

**Issue by rems360bulbi** [TheArmKing/osxGlow#2]
It worked well for months but now it doesn't load anymore with the latest CS:GO update ! 
Could you check please ? I wil contribute with donation if you fix it ;)
Thanks in advance

**Comment by TheArmKing** [comment]
Function signature changed. I have updated it and uploaded the newly compiled dylib. Could you confirm that it works now?

**Comment by rems360bulbi** [comment]
Thanks it works on MBP Retina on Catalina. Thank you so much ;)
